media:
  input: static/images/uploads
  output: /images/uploads

content:
  - name: eventi
    label: Eventi
    type: collection
    path: content/eventi
    format: yaml-frontmatter
    fields:
      - name: title
        label: Nome evento
        type: string
      - name: date
        label: Data evento
        type: date
      - name: image
        label: Immagine evento
        type: image
      - name: registration_url
        label: Link registrazione
        type: string

settings:
  hide: true
