backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored here
public_folder: "/images/uploads" # The public URL of the media folder

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
